name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: habrdb  # имя базы данных
          POSTGRES_USER: user   # имя пользователя
          POSTGRES_PASSWORD: user  # пароль
        ports:
          - 23210:5432          # мапим порт 5432 PostgreSQL на порт 23210
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          SPRING_APPLICATION_NAME: FirstLab
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgreDB:5432/first
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: user
          SPRING_JPA_SHOW_SQL: true
          SPRING_JPA_PROPERTIES_JAVAX_PERSISTENCE_PROVIDER: org.eclipse.persistence.jpa.PersistenceProvider
          SPRING_JPA_PROPERTIES_ECLIPSE_LINK_LOGGING_LEVEL: FINE
          SPRING_JPA_PROPERTIES_ECLIPSE_LINK_LOGGING_FILE: stdout
          SPRING_JPA_HIBERNATE_DDL_AUTO: create
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test